name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          git checkout -b temp-hf-deploy
          git rm -rf assets/
          git commit -m "chore: remove assets for Hugging Face deployment" --allow-empty
          git push --force https://quochiepho:$HF_TOKEN@huggingface.co/spaces/quochiepho/doctorAI temp-hf-deploy:main
